### ISSUE TITLE
pipes2js not found

### ISSUE THREAD

**Issue by Free16t** [ericabouaf/pipes2js#1]
Hi,

As Yahoo Pipes is closing, I'm looking for alternatives like pipes2js. 
However, when I did `npm install -g pipes2js` I have a 404 error and npm told me that pipes2js is not in the npm repository.

Sincerely

**Comment by ericabouaf** [comment]
Thx, I probably never pushed it. It's fixed: https://www.npmjs.com/package/pipes2js

Cheers

**Comment by Free16t** [comment]
Perfect, thank a lot for your help.

Regards
